### ISSUE TITLE
The question about Multiprocessing error

### ISSUE THREAD

**Issue by LGZ-BIT** [ZhengyiLuo/PULSE#12]
Hi, when I try to train SMPL downstream tasks, some errors occurred:
`Traceback (most recent call last):
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/git_code/PULSE-master/phc/utils/motion_lib_smpl.py", line 172, in load_motion_with_skeleton
    queue.put(res)
  File "<string>", line 2, in put
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/managers.py", line 850, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
`
`Traceback (most recent call last):
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/managers.py", line 243, in serve_client
    request = recv()
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 496, in rebuild_storage_fd
    fd = df.detach()
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/reduction.py", line 188, in recv_handle
    with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s:
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/socket.py", line 543, in fromfd
    nfd = dup(fd)
OSError: [Errno 24] Too many open files
`

**Comment by LGZ-BIT** [comment]
problem solved
